const staticData = [
  {
    imgloc: "https://i.ibb.co/Y0qjtrX/hdfcbank.png",
    lastUpdated: "54m",
    headerName: "HDFC Bank Limited",
    type: "Banking",
    price: "1,436.80",
    inOrDec: "126",
    hasIncreased: true,
    byPercentage: "2.34",
    reasonForBuying: "Buy The dip",
    potentialReturn: "1.13",
    projectedExit: "3 mo",
    lastRun: [true, false, false, true, true, false, true, true],
    winRate: "76",
  },
  {
    imgloc: "https://i.ibb.co/yS3r4gW/maruti-suzuki-logo-png-transparent.png",
    lastUpdated: "10m",
    headerName: "Maruti Suzuki",
    type: "Automobile",
    price: "7,429.00",
    inOrDec: "189.70",
    hasIncreased: true,
    byPercentage: "1.46",
    reasonForBuying: "Bull market",
    potentialReturn: "3.39",
    projectedExit: "6 mo",
    lastRun: [false, true, true, false, true, true, true, true],
    winRate: "86",
  },
  {
    imgloc: "https://i.ibb.co/cxNQj1p/itc-limited-logo-png-transparent.png",
    lastUpdated: "54m",
    headerName: "ITC",
    type: "Conglomerate",
    price: "252.70",
    inOrDec: "2.15",
    hasIncreased: false,
    byPercentage: "0.84",
    reasonForBuying: "Buy The dip",
    potentialReturn: "1.13",
    projectedExit: "1 week",
    lastRun: [true, true, true, true, true, false, true, true],
    winRate: "76",
  },
  {
    imgloc: "https://i.ibb.co/QFS1Rjm/tata.png",
    lastUpdated: "54m",
    headerName: "Tata Motors",
    type: "Automobile",
    price: "432.40",
    inOrDec: "98.15",
    hasIncreased: true,
    byPercentage: "12.34",
    reasonForBuying: "Buy before reversal",
    potentialReturn: "2.83",
    projectedExit: "6 mo",
    lastRun: [true, true, true, true, true, true, true, true],
    winRate: "92",
  },
];
export default staticData;
